version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: api
    volumes:
      - ./app/picture/data:/code/app/picture/data
      - ./app/picture/logs:/code/app/picture/logs
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: bash -c 'cd database/; alembic revision --autogenerate -m "Initial"; alembic upgrade head; cd ..; python main.py'
