version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  api:
    build: .
    container_name: api
    volumes:
      - ./app/picture/data:/code/app/picture/data
      - ./app/picture/logs:/code/app/picture/logs
    ports:
      - "8080:8080"